//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoseOfHope.Exception {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DoseOfHope.Exception.ResourceErrorMessages", typeof(ResourceErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bairro é obrigatório..
        /// </summary>
        public static string BAIRRO_OBRIGATORIO {
            get {
                return ResourceManager.GetString("BAIRRO_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cidade é obrigatório..
        /// </summary>
        public static string CIDADE_OBRIGATORIO {
            get {
                return ResourceManager.GetString("CIDADE_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Complemento é obrigatório.
        /// </summary>
        public static string COMPLEMENTO_OBRIGATORIO {
            get {
                return ResourceManager.GetString("COMPLEMENTO_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Um usuário com este CPF já está cadastrado..
        /// </summary>
        public static string CPF_JA_CADASTRADO {
            get {
                return ResourceManager.GetString("CPF_JA_CADASTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF é obrigatório.
        /// </summary>
        public static string CPF_OBRIGATORIO {
            get {
                return ResourceManager.GetString("CPF_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data nascimento é obrigatório..
        /// </summary>
        public static string DATA_NASCIMENTO_OBRIGATORIO {
            get {
                return ResourceManager.GetString("DATA_NASCIMENTO_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Um usuário com este e-mail já está cadastrado..
        /// </summary>
        public static string EMAIL_JA_CADASTRADO {
            get {
                return ResourceManager.GetString("EMAIL_JA_CADASTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email é obrigatório..
        /// </summary>
        public static string EMAIL_OBRIGATORIO {
            get {
                return ResourceManager.GetString("EMAIL_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro desconhecido..
        /// </summary>
        public static string ERRO_DESCONHECIDO {
            get {
                return ResourceManager.GetString("ERRO_DESCONHECIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Genêro é obrigatório..
        /// </summary>
        public static string GENERO_OBRIGATORIO {
            get {
                return ResourceManager.GetString("GENERO_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail ou Senha inválidos..
        /// </summary>
        public static string LOGIN_INVALIDO {
            get {
                return ResourceManager.GetString("LOGIN_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome é obrigatório..
        /// </summary>
        public static string NOME_OBRIGATORIO {
            get {
                return ResourceManager.GetString("NOME_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Número residencial é obrigatório.
        /// </summary>
        public static string NUMERO_OBRIGATORIO {
            get {
                return ResourceManager.GetString("NUMERO_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RG deve conter no mínimo 5 caracteres..
        /// </summary>
        public static string RG_DEVE_CONTER_5_DIGITOS {
            get {
                return ResourceManager.GetString("RG_DEVE_CONTER_5_DIGITOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RG é obrigatório..
        /// </summary>
        public static string RG_OBRIGATORIO {
            get {
                return ResourceManager.GetString("RG_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Rua é obrigatório..
        /// </summary>
        public static string RUA_OBRIGATORIO {
            get {
                return ResourceManager.GetString("RUA_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha é obrigatório..
        /// </summary>
        public static string SENHA_OBRIGATORIO {
            get {
                return ResourceManager.GetString("SENHA_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Telefone deve conter 11 dígitos..
        /// </summary>
        public static string TELEFONE_DEVE_CONTER_11_DIGITOS {
            get {
                return ResourceManager.GetString("TELEFONE_DEVE_CONTER_11_DIGITOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Telefone é obrigatório..
        /// </summary>
        public static string TELEFONE_OBRIGATORIO {
            get {
                return ResourceManager.GetString("TELEFONE_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário não encontrado..
        /// </summary>
        public static string USUARIO_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("USUARIO_NAO_ENCONTRADO", resourceCulture);
            }
        }
    }
}
